export enum ACTIONS {
  'LOGIN' = 'LOGIN',
  'LOGIN_SUCCESS' = 'LOGIN_SUCCESS',
  'NOT_LOGED_IN' = 'NOT_LOGED_IN',
  'NEEDS_TO_REGISTER' = 'NEEDS_TO_REGISTER',
  'REGISTER' = 'REGISTER',
  'REGISTER_SUCCESS' = 'REGISTER_SUCCESS',
}
